spring:
  application:
    name: drivingLicenceID

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: melina
    password:
    url: jdbc:h2:./db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=MYSQL;

  jpa:
    hibernate:
      ddl-auto: create

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: utf-8

server:
  port: 8080